### ISSUE TITLE
Create a chat forum (Discord)

### ISSUE THREAD

**Issue by michaeldacanay** [1360119047/calorieApp_server#2]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 1360119047** [comment]
see in discussion

**Comment by michaeldacanay** [comment]
As per discussion was Yasitha, including link here for better visibility: https://github.com/1360119047/calorieApp_server/discussions/18
